/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;



/**
 *
 * @author Rovinsan
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        setTitle("User Login");
    }

    /**
     * This/ method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        username_Lable = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        password_lable = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        LoginjButton1 = new javax.swing.JButton();
        canclejButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Message = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        setForeground(new java.awt.Color(51, 204, 255));
        setLocation(new java.awt.Point(0, 0));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        username_Lable.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        username_Lable.setText("User Name");
        username_Lable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(username_Lable);
        username_Lable.setBounds(160, 160, 127, 30);

        usernameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(usernameField);
        usernameField.setBounds(290, 160, 149, 30);

        password_lable.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        password_lable.setText("Password");
        getContentPane().add(password_lable);
        password_lable.setBounds(160, 200, 127, 27);

        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(290, 200, 149, 29);

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 90, 132, 53);

        LoginjButton1.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        LoginjButton1.setText("Login");
        LoginjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginjButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(LoginjButton1);
        LoginjButton1.setBounds(290, 290, 110, 23);

        canclejButton1.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        canclejButton1.setText("Cancle");
        canclejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canclejButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(canclejButton1);
        canclejButton1.setBounds(290, 320, 110, 23);

        jLabel2.setBackground(java.awt.SystemColor.activeCaption);
        jLabel2.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel2MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(234, 46, 219, 47);

        Message.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Message.setForeground(java.awt.Color.red);
        getContentPane().add(Message);
        Message.setBounds(270, 240, 235, 32);

        setSize(new java.awt.Dimension(816, 439));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void canclejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canclejButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_canclejButton1ActionPerformed

    private void LoginjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginjButton1ActionPerformed
        // TODO add your handling code here:
        String password = jPasswordField1.getText();
        String username = usernameField.getText();
        
        if(password.contains("admin")&& username.contains("admin")){
            jPasswordField1.setText("");
            usernameField.setText("");
            //System.exit(0);
            welcome w = new welcome();
           
            w.setVisible(true);
            jPasswordField1.setText("");
            usernameField.setText("");
        }
        else{
            //JOptionPane.showMessageDialog(null,"This password is exteramly Wrong","Wrong password",JOptionPane.ERROR_MESSAGE);
            jPasswordField1.setText("");
           // usernameField.setText("");
            Message.setText("Incorrect username or password");
            
        }
    }//GEN-LAST:event_LoginjButton1ActionPerformed

    private void jLabel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginjButton1;
    private javax.swing.JLabel Message;
    private javax.swing.JButton canclejButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel password_lable;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel username_Lable;
    // End of variables declaration//GEN-END:variables
}
