/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Rovinsan
 */
public class second_GUI extends javax.swing.JFrame {

    /**
     * Creates new form second_GUI
     */
    public second_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        second_pannel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        third_pannel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        toyota_Button = new javax.swing.JButton();
        nissan_Button = new javax.swing.JButton();
        mazda_Button = new javax.swing.JButton();
        suzuki_Button = new javax.swing.JButton();
        kia_Button = new javax.swing.JButton();
        van_Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        first_pannel = new javax.swing.JPanel();
        van_panel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        suzuki_panel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        kia_panel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        mazda_panel = new javax.swing.JPanel();
        nissan_panel = new javax.swing.JPanel();
        toyota_panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        second_pannel.setBackground(new java.awt.Color(204, 0, 204));
        second_pannel.setLayout(null);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TOYOTA");
        second_pannel.add(jLabel2);
        jLabel2.setBounds(50, 70, 70, 20);

        third_pannel.setBackground(new java.awt.Color(51, 51, 51));
        third_pannel.setLayout(new java.awt.BorderLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(120, 126, 141));
        jPanel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.setLayout(null);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 153));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 153));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(109, 32, 10, 357);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 153));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(117, 66, 470, 10);

        jPanel2.setBackground(new java.awt.Color(170, 93, 124));
        jPanel2.setLayout(null);

        toyota_Button.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        toyota_Button.setText("Toyota");
        toyota_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(217, 194, 222), new java.awt.Color(216, 186, 231), new java.awt.Color(131, 74, 219), null));
        toyota_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toyota_ButtonActionPerformed(evt);
            }
        });
        jPanel2.add(toyota_Button);
        toyota_Button.setBounds(10, 120, 80, 20);

        nissan_Button.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        nissan_Button.setText("Nissan");
        nissan_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(217, 194, 222), new java.awt.Color(216, 186, 231), new java.awt.Color(131, 74, 219), null));
        nissan_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nissan_ButtonActionPerformed(evt);
            }
        });
        jPanel2.add(nissan_Button);
        nissan_Button.setBounds(10, 150, 80, 20);

        mazda_Button.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        mazda_Button.setText("Mazda");
        mazda_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(217, 194, 222), new java.awt.Color(216, 186, 231), new java.awt.Color(131, 74, 219), null));
        mazda_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mazda_ButtonActionPerformed(evt);
            }
        });
        jPanel2.add(mazda_Button);
        mazda_Button.setBounds(10, 180, 80, 20);

        suzuki_Button.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        suzuki_Button.setText("Suzuki");
        suzuki_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(217, 194, 222), new java.awt.Color(216, 186, 231), new java.awt.Color(131, 74, 219), null));
        suzuki_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suzuki_ButtonActionPerformed(evt);
            }
        });
        jPanel2.add(suzuki_Button);
        suzuki_Button.setBounds(10, 210, 80, 20);

        kia_Button.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        kia_Button.setText("Kia");
        kia_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(217, 194, 222), new java.awt.Color(216, 186, 231), new java.awt.Color(131, 74, 219), null));
        kia_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kia_ButtonActionPerformed(evt);
            }
        });
        jPanel2.add(kia_Button);
        kia_Button.setBounds(10, 240, 80, 20);

        van_Button.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        van_Button.setText("Van");
        van_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(217, 194, 222), new java.awt.Color(216, 186, 231), new java.awt.Color(131, 74, 219), null));
        van_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                van_ButtonActionPerformed(evt);
            }
        });
        jPanel2.add(van_Button);
        van_Button.setBounds(10, 270, 80, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 30, 100, 360);

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 24, 104));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Car Rental System");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 20, 230, 40);

        first_pannel.setBackground(new java.awt.Color(51, 0, 51));
        first_pannel.setLayout(null);

        van_panel.setBackground(new java.awt.Color(255, 153, 153));
        van_panel.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("VAN PANEL");
        van_panel.add(jLabel8);
        jLabel8.setBounds(0, 0, 110, 20);

        suzuki_panel.setBackground(new java.awt.Color(0, 255, 51));
        suzuki_panel.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SUZUKI PANEL");
        suzuki_panel.add(jLabel6);
        jLabel6.setBounds(0, 0, 130, 20);

        kia_panel.setBackground(new java.awt.Color(240, 38, 229));
        kia_panel.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("KIA PANEL");
        kia_panel.add(jLabel7);
        jLabel7.setBounds(0, 0, 100, 20);

        mazda_panel.setBackground(new java.awt.Color(0, 51, 51));
        mazda_panel.setLayout(null);

        nissan_panel.setBackground(new java.awt.Color(153, 153, 0));
        nissan_panel.setLayout(null);

        toyota_panel.setBackground(new java.awt.Color(51, 0, 51));
        toyota_panel.setLayout(null);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TOYOTA PANEL");
        toyota_panel.add(jLabel3);
        jLabel3.setBounds(0, 0, 160, 40);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        toyota_panel.add(jLabel10);
        jLabel10.setBounds(110, 160, 90, 30);

        nissan_panel.add(toyota_panel);
        toyota_panel.setBounds(0, 0, 470, 310);

        jLabel4.setBackground(new java.awt.Color(153, 153, 0));
        jLabel4.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NISSAN PANEL");
        nissan_panel.add(jLabel4);
        jLabel4.setBounds(0, 0, 140, 30);

        mazda_panel.add(nissan_panel);
        nissan_panel.setBounds(0, 0, 480, 340);

        jLabel5.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MAZDA PANEL");
        mazda_panel.add(jLabel5);
        jLabel5.setBounds(0, 0, 140, 30);

        kia_panel.add(mazda_panel);
        mazda_panel.setBounds(0, 0, 470, 310);

        suzuki_panel.add(kia_panel);
        kia_panel.setBounds(0, 0, 470, 310);

        van_panel.add(suzuki_panel);
        suzuki_panel.setBounds(0, 0, 470, 310);

        first_pannel.add(van_panel);
        van_panel.setBounds(0, 0, 470, 310);

        jPanel1.add(first_pannel);
        first_pannel.setBounds(120, 80, 470, 310);

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 153));
        jButton1.setText("Booking");
        jPanel1.add(jButton1);
        jButton1.setBounds(480, 20, 65, 25);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 660, 440);

        setSize(new java.awt.Dimension(680, 486));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void toyota_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toyota_ButtonActionPerformed
        // TODO add your handling code here:
        first_pannel.removeAll();
        first_pannel.repaint();
        first_pannel.revalidate();
        
        first_pannel.add(toyota_panel);
        first_pannel.repaint();
        first_pannel.revalidate();
    }//GEN-LAST:event_toyota_ButtonActionPerformed

    private void nissan_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nissan_ButtonActionPerformed
        // TODO add your handling code here:
        first_pannel.removeAll();
        first_pannel.repaint();
        first_pannel.revalidate();
        
        first_pannel.add(nissan_panel);
        first_pannel.repaint();
        first_pannel.revalidate();
    }//GEN-LAST:event_nissan_ButtonActionPerformed

    private void mazda_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mazda_ButtonActionPerformed
        // TODO add your handling code here:
        first_pannel.removeAll();
        first_pannel.repaint();
        first_pannel.revalidate();
        
        first_pannel.add(mazda_panel);
        first_pannel.repaint();
        first_pannel.revalidate();
    }//GEN-LAST:event_mazda_ButtonActionPerformed

    private void suzuki_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suzuki_ButtonActionPerformed
        // TODO add your handling code here:
        first_pannel.removeAll();
        first_pannel.repaint();
        first_pannel.revalidate();
        
        first_pannel.add(suzuki_panel);
        first_pannel.repaint();
        first_pannel.revalidate();
    }//GEN-LAST:event_suzuki_ButtonActionPerformed

    private void kia_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kia_ButtonActionPerformed
        // TODO add your handling code here:
        first_pannel.removeAll();
        first_pannel.repaint();
        first_pannel.revalidate();
        
        first_pannel.add(kia_panel);
        first_pannel.repaint();
        first_pannel.revalidate();
    }//GEN-LAST:event_kia_ButtonActionPerformed

    private void van_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_van_ButtonActionPerformed
        // TODO add your handling code here:
        first_pannel.removeAll();
        first_pannel.repaint();
        first_pannel.revalidate();
        
        first_pannel.add(van_panel);
        first_pannel.repaint();
        first_pannel.revalidate();
    }//GEN-LAST:event_van_ButtonActionPerformed

    private void jPanel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel1AncestorAdded
        // TODO add your handling code here:
        first_pannel.removeAll();
         first_pannel.repaint();
        first_pannel.revalidate();
    }//GEN-LAST:event_jPanel1AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(second_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(second_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(second_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(second_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new second_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel first_pannel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton kia_Button;
    private javax.swing.JPanel kia_panel;
    private javax.swing.JButton mazda_Button;
    private javax.swing.JPanel mazda_panel;
    private javax.swing.JButton nissan_Button;
    private javax.swing.JPanel nissan_panel;
    private javax.swing.JPanel second_pannel;
    private javax.swing.JButton suzuki_Button;
    private javax.swing.JPanel suzuki_panel;
    private javax.swing.JPanel third_pannel;
    private javax.swing.JButton toyota_Button;
    private javax.swing.JPanel toyota_panel;
    private javax.swing.JButton van_Button;
    private javax.swing.JPanel van_panel;
    // End of variables declaration//GEN-END:variables
}
